[1.5.0]
Title = "Version 1.5.0"
Description = [ "Use configparser to change the values in change_config_file().", "Change /etc/mysql/mysql.conf.d/mysqld.cnf permissions in code rather in action setup.",]
GitHubIssues = [ 6,]

[1.4.1]
Title = "Version 1.4.1"
Description = [ "V1.4.0 tag not pushed correctly (multiple tags).",]
GitHubIssues = [ 5,]

[1.4.0]
Title = "Version 1.4.0"
Description = [ "Sortout GitHub Actions", "- Sort out CI.", "- Release to PyPI only run if a tag is pushed.",]
GitHubIssues = [ 5,]

[1.3.4]
Title = "Version 1.3.4"
Description = [ "Multiple enhancements and bug fixes", "Remove references to p_crash from beescript.beescript (GitHub issue #2).", "Update GitHub workflow titles (GitHub issue #3).",]
GitHubIssues = [ 3, 4,]

[1.3.3]
Title = "Version 1.3.3"
Description = [ "Version 1.3.4", "[Bug]: uwsgi internal server error", "Remove references to p_crash from beescript.beescript (GitHub issue #2).", "Update GitHub workflow titles (GitHub issue #3).",]

[1.3.2]
Title = "Version 1.3.2"
Description = [ "Version 1.3.2", "Creation of the project", "List all the changes to the project here.", "Changes listed here will be in the release notes under the above heading.",]
